### PR TITLE
Fix modal issue

### LINKED ISSUE #96: Modals aren't working
@risu-kun and I noticed that none of the modals are working in our local environments. Let's fix this!

### PR DESCRIPTION
**Pull request by risu-kun**
Fixes #96... I followed these two SO posts linked by @enico:

- http://stackoverflow.com/questions/10636667/bootstrap-modal-appearing-under-background
- http://stackoverflow.com/questions/18580203/bootstrap-modal-window-is-grayed-out

The solution in the second one, changing the z-index, is what fixes the issue. So the adjustments I did to the `categories` detail page aren't really necessary, if we need to get rid of them to deal with the merge conflict.

### CODE REVIEW

**Comment by kenmazaika** [comment]
Seems reasonable, but has merge conflicts so I can't merge it.

**Comment by risu-kun** [comment]
Yeah, I'm trying to figure out how to resolve them. :confused: Have enlisted @enico's help.

**Comment by kenmazaika** [comment]
Awesome!  Good luck!

**Comment by risu-kun** [comment]
Man! Sorry that was so messy. I'm still getting the hang of merge conflicts.

**Comment by kenmazaika** [comment]
Awesome!

**Pull request merged**
