### PR TITLE
Allow markdown posts and comments

### LINKED ISSUE #77: As a user, I should be able to format my posts with markdown
The posts `message` field should be displayed as markdown.  There are many gems to do this.

### PR DESCRIPTION
**Pull request by risu-kun**
Resolves #77.

I added the [pagedown-bootstrap-rails](https://github.com/hughevans/pagedown-bootstrap-rails) gem and it played very nicely.

screenshot from 2016-04-19 22 50 32

### CODE REVIEW

**Comment by kenmazaika** [comment]
Looks good to me!  @amarkpark you offered to be a second set of eyes on PRs.  What are your thoughts?

**Comment by amarkpark** [comment]
So far looks good.  I'll pull it down and do a quick sanity check.

**Comment by amarkpark** [comment]
OK, two comments:
1) code editor handling of code snippets is a tad odd.  Basically have to format it first and then select it and format it as code.  **_That behavior is likely inherent in the gem._**
2) As it stands adding a new post with the markdown window and the preview pane (might wish to label it in the view) if the Message of the post is more than a line or two the "Submit" button disappears under the footer and there appears to be no scroll bar to get down to it, one has to enlarge the browser window to see the submit button.  See photo with no submit button and no scroll bar:
screen shot 2016-04-20 at 11 38 59 am

Note: I cannot rule out limitations of my environment, so someone should please verify this behavior!

**Comment by kenmazaika** [comment]
Thoughts on merging this and then making separate issues for it?

**Comment by risu-kun** [comment]
That may make it easier for everyone to play with and find more bugs, @kenmazaika :laughing: 

Thanks for your QA expertise, @amarkpark!

**Comment by amarkpark** [comment]
I'm good with merging this and creating issues for specific points.  Code seems solid.  :-)

**Pull request merged**
