### PR TITLE
For review for now-Changed BGColor/Add BGPattern

### PR DESCRIPTION
**Pull request by enico**
I originally had weird colors going on in the background, preventing the signup/login form text from showing. BG color was black so it was a little dark. Added pattern instead. 
screenshot 2016-04-01 15 34 00

Also, there is some padding before the nav, should that be reduced?

screenshot 2016-04-01 15 33 36

### CODE REVIEW

**Comment by enico** [comment]
Forgot to put original png
screenshot 2016-04-01 15 51 19
I think @cacauzen had white background in her mockup, I think that looks great to and can do that instead of pattern for whatever is best.

**Comment by cacauzen** [comment]
@enico Yeah that's better. The body has a 70px padding-top because the nav-bar is fixed. It was hiding all the devise forms and the green text before the image was added.  We can fix that by either changing the body padding-top to around 50px orrrrr we can add a negative padding-top or margin-top to the dive containing the splash page image, so it gets pulled up a little :)

**Comment by cacauzen** [comment]
@enico I think we should talk about what to do for the design part of this project before adding backgrounds fonts  and colors... otherwise we will end up with a crazy looking app hahaha

**Comment by enico** [comment]
@cacauzen hehe yep that sounds good.

**Comment by cacauzen** [comment]
I do like the gray pattern though! maybe we can do green accents, gray background?

**Comment by enico** [comment]
Yeah, I can see that. Maybe something accented on the navbar as well?

**Comment by cacauzen** [comment]
digital-medien

I like the feel of this one. maybe a not so bright green? I don't mean to copy this but i like the color scheme a lot

**Comment by cacauzen** [comment]
screenshot 2016-04-01 17 17 38
let me know what you think :dancers:

**Comment by cacauzen** [comment]
and then maybe we substitute the grey color for the background and see which works best :D

**Comment by enico** [comment]
ooo nice yeah that can work.

**Pull request closed without merging**
