### PR TITLE
Added user controller, user show view and gravtastic gem

### PR DESCRIPTION
**Pull request by NKHolton**
This is to fix Issue #37.  

- Added a user controller and associated show.html.erb view for a user- included email and date joined.
- Added gravtastic gem to use a gravatar within the My Profile page but haven't set everything up with that yet (only invluded it in the User model).  @robertsapunarich- didn't you do some work on the last open-source group project DEFCON app with gravatars?  Not 100% sure how to do and would love to pair program with someone.  
- Note: I try to sign-up or sign-in on the website but it's throwing an error related to no routes set up for /users/sign-up.  Is this something I should do or something that I'm not understanding?
- I created a user in the console so I could at least see what the view looked like (see screenshot).  No styling added yet.
usershowview

### CODE REVIEW

**Comment by kenmazaika** [comment]
Looks good to me.  I think @cacauzen was working on implementing the sign in functionality, and I think it may be in an incomplete state currently.

The code looks good.  I suggest adding a controller test.  Then once we add a test, let's merge this in.

**Comment by NKHolton** [comment]
Ok great, will add a test.  I've seen the conversations about setting some design standards which I think is great.  Unfortunately unable to make the next two Thursday team meetings but will listen to the recordings so I'm in line with everything going on.

**Comment by kenmazaika** [comment]
Sounds like a plan!  Thanks for the heads up.

**Comment by NKHolton** [comment]
Ok I added a test for the users controller but don't actually know if it's working correctly.  Given there are probably so many tests is there a log anywhere to check?  I tried adding a 2nd test to 'require users to be logged in to see their profile page' but didn't fully implement it and don't know if this is a bad test to do?  Need to refresh my TDD knowledge now and forgetting if someone is not signed in that they shouldn't see a link to My Profile, right?  But they could still somehow go to the URL for someone's profile.

So the tests still need to be perfected here in my opinion plus I'm happy to continue the gravatar implementation or My Profile in the coming week and/or happy to accept another issue that you can assign to me!  Thanks!

**Comment by kenmazaika** [comment]
The test looks great, Natalie!  Thumbs up!

**Comment by NKHolton** [comment]
Great!  Feel free to assign me another issue today or I can snag one tomorrow!

**Comment by kenmazaika** [comment]
Will do!

**Pull request merged**
